# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jane Wu
tagline:          ""
description:      ""
url:              https://janewuco.github.io

author:
  name:           'Jane Wu'
  url:            https://twitter.com/cryp_TOTO


plugins:          [jekyll-paginate]
paginate:         3
paginate_path:    "site/:num"
timezone            : null

google_analytics: ""


show_excerpts: true
# Handling Readings
safe                : false
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

twitter_username:
github_username:
linkedin_username:




# github:
#  repo:           https://github.com/
