# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jane Wu
tagline:          ''
description:      ''
url:              https://janewu.co
baseurl:          /

author:
  name:           'Jane Wu'
  url:            https://twitter.com/cryp_TOTO


plugins:          [jekyll-paginate]
paginate:         5
paginate_path:    "site/:num"


collections:
  blog:
    output: true
  sinoblog:
    output: true
# Custom vars
version:          2.1.0

# github:
#  repo:           https://github.com/
